### PR TITLE
inference results for 11.03.23

### PR DESCRIPTION
**Pull request by bkotzen**

### CODE REVIEW

**Comment by bkotzen** [comment]
@martinjankowiak new inference results! had to subsample the GISAID metadata to get it to work in memory; hopefully there will be a more elegant solution later

**Comment by bkotzen** [comment]
@martinjankowiak updating with 11.17 as well!

**Comment by martinjankowiak** [comment]
@bkotzen if you're doing data subsampling can you note that in the corresponding pair of metadata.txt with a new entry? something like
`Percent of raw data included in inference: 93%`

EDIT: actually why are the numbers of regions/sequences so different between the two??

**Comment by bkotzen** [comment]
Hey @martinjankowiak yes I am doing some significant downsampling to meet compute restrictions. However, I'm finalizing a fix right now and I will re-run results for dates where down-sampling occurred. I should be able to impute some better results by EOW and that will resolve this issue!

**Comment by bkotzen** [comment]
Just added in some more recent results - to make sure everything works. Now that I know it works on current data I can fix 11.17.2023

**Comment by martinjankowiak** [comment]
@bkotzen how does the subsampling work? when you update the PR can you please make sure to:
- delete all irrelevant/stale files
- update metadata.txt everywhere where necessary to indicate to indicate that data was subsampled

**Comment by bkotzen** [comment]
The subsampling randomly selected a proportion of the samples in the GISAID metadata and ran PyR0 and BVAS only on those samples. 

I have now made some tweaks to my compute infrastructure and the preprocessing code in order to handle the large number of sequences. 

The timeline is:
11/03 started subsampling, now I'm re-doing this run
11/17 significant subsampling, but I just deleted the original results ([5c68de7](https://github.com/broadinstitute/bvas/pull/15/commits/5c68de70c9b89397e71fa56423d6626af5182621)) and replaced them with non-subsampled results ([e10667a](https://github.com/broadinstitute/bvas/pull/15/commits/e10667a4dbac586763314970700d9d6c7da7d49d))
11/28 by this point I had created a solution where I didn't need to subsample anymore so these results are fine

**Comment by martinjankowiak** [comment]
@bkotzen i see so we're waiting for you to replace the 11/03  run?

**Comment by bkotzen** [comment]
Yep! 11/03 is almost done - will put it here ASAP

**Comment by bkotzen** [comment]
Ok @martinjankowiak! Everything is all set now 💪🏼 😤

**Review by martinjankowiak — APPROVED** [review]
great thanks @bkotzen !

**Pull request merged**
