### PR TITLE
inference results for 2023-07-11

### PR DESCRIPTION
**Pull request by bkotzen**
Hey @martinjankowiak here are new BVAS results!

### CODE REVIEW

**Comment by martinjankowiak** [comment]
@bkotzen if you're going to be doing this more often now can we revisit the workflow? i suggest the following:
- you make a PR to `main` instead of `pipeline`
- you exactly reproduce the file name conventions etc in `main`, meaning in particular
  - the folder in /paper/ is of the form `09.22.22` (dot separators, 2-digit year, etc)
  - the file names are allele_summary.csv, growth_rates_summary.csv, metadata.txt, pip_ranked_alleles.png, top_growth_rates.png
  - the README.md is updated to expand this comma-separated list: More recent inference results are also available: [08.10.22](https://github.com/broadinstitute/bvas/blob/main/paper/08.10.22), [09.22.22](https://github.com/broadinstitute/bvas/blob/main/paper/09.22.22), [05.18.23](https://github.com/broadinstitute/bvas/blob/main/paper/05.18.23), [06.15.23](https://github.com/broadinstitute/bvas/blob/main/paper/06.15.23), and [06.30.23](https://github.com/broadinstitute/bvas/blob/main/paper/06.30.23).
  - no other changes are introduced

**Comment by bkotzen** [comment]
Hey @martinjankowiak, sorry it has taken me so long to get back to you on this! I've incorporated these suggestions and you can now find a new PR in the preferred style [here](https://github.com/broadinstitute/bvas/pull/10). 

I would also like to propose another PR for broadinstitute/bvas:pipeline to add `allele_table.ipynb` and `growth_rate_table.ipynb` as these two notebooks are used to produce `pip_ranked_alleles.png` and `top_growth_rates.png`.

**Comment by martinjankowiak** [comment]
@bkotzen the july results were never merged so i merged them in https://github.com/broadinstitute/bvas/pull/11
can you please check that everything looks right?

**Comment by martinjankowiak** [comment]
@bkotzen feel free to open other PRs as needed. closing this one now since it's no longer relevant

**Comment by bkotzen** [comment]
Thanks Martin! It all looks good to me.

**Pull request closed without merging**
